[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "draxc", email = "sasacikota97@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "bcrypt==4.0.1",
    "boto3>=1.43.102",
    "passlib[bcrypt]==1.7.4",
    "pyjwt>=2.14.0",
    "pyotp>=2.10.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "qrcode>=8.2",
    "redis>=8.1.0",
]

