name: 02 - tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  testing_with_pytest:
    runs-on: ubuntu-latest
    steps:
      #  download our repo
      - name: clone repo
        uses: actions/checkout@v7

      - name: install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9

      - name: run test!!!
        working-directory: app/project
        run: uv run -m pytest .